# Generated by Django 4.1 on 2022-09-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='telefone',
            field=models.CharField(max_length=13, verbose_name='Telefone'),
        ),
    ]
