# Generated by Django 4.1 on 2022-09-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_leitor_email_alter_leitor_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[(True, 'Em andamento'), (False, 'Finalizado')], default='Em andamento', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='status',
            field=models.CharField(choices=[(True, 'Desbloqueado'), (False, 'Bloqueado')], default='Desbloqueado', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[(True, 'Disponível'), (False, 'Indisponível')], default='Disponível', max_length=12, verbose_name='Status'),
        ),
    ]
